### ISSUE TITLE
Statically type the codebase

### ISSUE THREAD

**Issue by eztaah** [c2i-junia/rustcraft#148]
You can start by statically typing some variables in the codebase (very easy things to do to start working on this project).

**Comment by AudranTourneur** [comment]
Instead of "statically type the codebase" I think you meant "add explicit types to variable declarations" 
I honestly don't know if it's best to add explicit types to let declarations everywhere or not, some people talk about it online but I feel like it's up for personal preference? :thinking: 
https://stackoverflow.com/questions/45461499/when-to-be-explicit-with-type-annotation
